version: 2
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X main.Version={{.Version}}

archives:
  - formats: [ 'tar.gz' ]
    format_overrides:
    - goos: windows
      formats: [ 'zip' ]
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: jonhadfield
    name: certreader
homebrew_casks:
  - repository:
      owner: jonhadfield
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    name: certreader
    homepage: "https://github.com/jonhadfield/certreader"
    description: "Print x509 certificate info."
    hooks:
       post:
         install: |
           if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
             system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/certreader"]
           end

