version: 2

builds:
  # --- macOS (Apple silicon) native ---
  - id: darwin-arm64
    env:
      - CGO_ENABLED=1
      - CC=clang
      - CXX=clang++
    goos: [darwin]
    goarch: [arm64]
    ldflags:
      - -X main.Version={{.Version}}

  # --- Linux amd64 via Zig cross-compiler ---
  - id: linux-amd64
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target x86_64-linux-gnu
      - CXX=zig c++ -target x86_64-linux-gnu
    goos: [linux]
    goarch: [amd64]
    ldflags:
      - -X main.Version={{.Version}}

  # --- Linux arm64 via Zig cross-compiler ---
  - id: linux-arm64
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target aarch64-linux-gnu
      - CXX=zig c++ -target aarch64-linux-gnu
    goos: [linux]
    goarch: [arm64]
    ldflags:
      - -X main.Version={{.Version}}

  # --- Windows amd64 via Zig cross-compiler (GNU) ---
  - id: windows-amd64
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target x86_64-windows-gnu
      - CXX=zig c++ -target x86_64-windows-gnu
    goos: [windows]
    goarch: [amd64]
    ldflags:
      - -X main.Version={{.Version}}

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: jonhadfield
    name: certreader
  prerelease: auto
  name_template: "{{ .Tag }}"
  extra_files:
    - glob: ./dist/certreader_darwin*.zip

# (GoReleaser note) brews is deprecated; migrate to homebrew_casks later.
brews:
  - name: certreader
    homepage: https://github.com/jonhadfield/certreader
    description: >
      Output detailed information about TLS certificates from local files, network hosts or clipboard.
    repository:
      owner: jonhadfield
      name: homebrew-certreader

announce:
  skip: true
