version: 2

builds:
  - id: linux-arm64
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -X main.Version={{.Version}}

archives:
  - formats:
      - tar.gz

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: jonhadfield
    name: certreader
  prerelease: auto
  name_template: "{{ .Tag }}"
